from thecoverproject import Consoles, Handhelds, Computers

home = "http://thecoverproject.net/"
index_opt = "&view={}"
_game_system_page = home + "view.php?cat_id={}"

_console_ids = {
    Consoles.three_do: 40,
    Consoles.amiga_cd_thirty_two: 48,
    Consoles.atari_two_six_zero_zero: 36,
    Consoles.atari_five_two_zero_zero: 34,
    Consoles.atari_seven_eight_zero_zero: 39,
    Consoles.atari_jaguar: 33,
    Consoles.atari_xe: 35,
    Consoles.colecovision: 38,
    Consoles.dreamcast: 1,
    Consoles.famicom_disk_system: 41,
    Consoles.gamecube: 2,
    Consoles.genesis: 3,
    Consoles.intellivision: 31,
    Consoles.jaguar_cd: 37,
    Consoles.neo_geo_cd: 32,
    Consoles.nes: 27,
    Consoles.nintendo_sixty_four: 4,
    Consoles.nintendo_switch: 62,
    Consoles.nintendo_wii: 18,
    Consoles.nintendo_wii_u: 58,
    Consoles.odyssey_two: 61,
    Consoles.pc_fx: 43,
    Consoles.philips_cdi: 51,
    Consoles.playstation_one: 5,
    Consoles.playstation_two: 6,
    Consoles.playstation_three: 19,
    Consoles.playstation_four: 60,
    Consoles.playstation_five: 63,
    Consoles.sega_thirty_two_x: 29,
    Consoles.sega_cd: 17,
    Consoles.sega_master_system: 30,
    Consoles.sega_saturn: 7,
    Consoles.super_nintendo: 8,
    Consoles.turbografx_sixteen: 42,
    Consoles.xbox: 9,
    Consoles.xbox_three_six_zero: 10,
    Consoles.xbox_one: 59,
    Consoles.xbox_series_x: 64,
}
consoles = {
    Consoles.three_do: _game_system_page.format(_console_ids[Consoles.three_do]),
    Consoles.amiga_cd_thirty_two: _game_system_page.format(_console_ids[Consoles.amiga_cd_thirty_two]),
    Consoles.atari_two_six_zero_zero: _game_system_page.format(_console_ids[Consoles.atari_two_six_zero_zero]),
    Consoles.atari_five_two_zero_zero: _game_system_page.format(_console_ids[Consoles.atari_five_two_zero_zero]),
    Consoles.atari_seven_eight_zero_zero: _game_system_page.format(_console_ids[Consoles.atari_seven_eight_zero_zero]),
    Consoles.atari_jaguar: _game_system_page.format(_console_ids[Consoles.atari_jaguar]),
    Consoles.atari_xe: _game_system_page.format(_console_ids[Consoles.atari_xe]),
    Consoles.colecovision: _game_system_page.format(_console_ids[Consoles.colecovision]),
    Consoles.dreamcast: _game_system_page.format(_console_ids[Consoles.dreamcast]),
    Consoles.famicom_disk_system: _game_system_page.format(_console_ids[Consoles.famicom_disk_system]),
    Consoles.gamecube: _game_system_page.format(_console_ids[Consoles.gamecube]),
    Consoles.genesis: _game_system_page.format(_console_ids[Consoles.genesis]),
    Consoles.intellivision: _game_system_page.format(_console_ids[Consoles.intellivision]),
    Consoles.jaguar_cd: _game_system_page.format(_console_ids[Consoles.jaguar_cd]),
    Consoles.neo_geo_cd: _game_system_page.format(_console_ids[Consoles.neo_geo_cd]),
    Consoles.nes: _game_system_page.format(_console_ids[Consoles.nes]),
    Consoles.nintendo_sixty_four: _game_system_page.format(_console_ids[Consoles.nintendo_sixty_four]),
    Consoles.nintendo_switch: _game_system_page.format(_console_ids[Consoles.nintendo_switch]),
    Consoles.nintendo_wii: _game_system_page.format(_console_ids[Consoles.nintendo_wii]),
    Consoles.nintendo_wii_u: _game_system_page.format(_console_ids[Consoles.nintendo_wii_u]),
    Consoles.odyssey_two: _game_system_page.format(_console_ids[Consoles.odyssey_two]),
    Consoles.pc_fx: _game_system_page.format(_console_ids[Consoles.pc_fx]),
    Consoles.philips_cdi: _game_system_page.format(_console_ids[Consoles.philips_cdi]),
    Consoles.playstation_one: _game_system_page.format(_console_ids[Consoles.playstation_one]),
    Consoles.playstation_two: _game_system_page.format(_console_ids[Consoles.playstation_two]),
    Consoles.playstation_three: _game_system_page.format(_console_ids[Consoles.playstation_three]),
    Consoles.playstation_four: _game_system_page.format(_console_ids[Consoles.playstation_four]),
    Consoles.playstation_five: _game_system_page.format(_console_ids[Consoles.playstation_five]),
    Consoles.sega_thirty_two_x: _game_system_page.format(_console_ids[Consoles.sega_thirty_two_x]),
    Consoles.sega_cd: _game_system_page.format(_console_ids[Consoles.sega_cd]),
    Consoles.sega_master_system: _game_system_page.format(_console_ids[Consoles.sega_master_system]),
    Consoles.sega_saturn: _game_system_page.format(_console_ids[Consoles.sega_saturn]),
    Consoles.super_nintendo: _game_system_page.format(_console_ids[Consoles.super_nintendo]),
    Consoles.turbografx_sixteen: _game_system_page.format(_console_ids[Consoles.turbografx_sixteen]),
    Consoles.xbox: _game_system_page.format(_console_ids[Consoles.xbox]),
    Consoles.xbox_three_six_zero: _game_system_page.format(_console_ids[Consoles.xbox_three_six_zero]),
    Consoles.xbox_one: _game_system_page.format(_console_ids[Consoles.xbox_one]),
    Consoles.xbox_series_x: _game_system_page.format(_console_ids[Consoles.xbox_series_x]),
}

_handheld_ids = {
    Handhelds.three_ds: 54,
    Handhelds.atari_lynx: 44,
    Handhelds.game_gear: 15,
    Handhelds.gameboy: 12,
    Handhelds.gameboy_advance: 13,
    Handhelds.gameboy_advance_video: 20,
    Handhelds.gameboy_color: 14,
    Handhelds.neo_geo_pocket: 45,
    Handhelds.neo_geo_pocket_color: 46,
    Handhelds.nintendo_ds: 11,
    Handhelds.playstation_portable: 16,
    Handhelds.playstation_portable_video: 52,
    Handhelds.playstation_vita: 55,
    Handhelds.virtual_boy: 56,
    Handhelds.wonderswan: 47,
    Handhelds.wonderswan_color: 50,
}
handhelds = {
    Handhelds.three_ds: _game_system_page.format(_handheld_ids[Handhelds.three_ds]),
    Handhelds.atari_lynx: _game_system_page.format(_handheld_ids[Handhelds.atari_lynx]),
    Handhelds.game_gear: _game_system_page.format(_handheld_ids[Handhelds.game_gear]),
    Handhelds.gameboy: _game_system_page.format(_handheld_ids[Handhelds.gameboy]),
    Handhelds.gameboy_advance: _game_system_page.format(_handheld_ids[Handhelds.gameboy_advance]),
    Handhelds.gameboy_advance_video: _game_system_page.format(_handheld_ids[Handhelds.gameboy_advance_video]),
    Handhelds.gameboy_color: _game_system_page.format(_handheld_ids[Handhelds.gameboy_color]),
    Handhelds.neo_geo_pocket: _game_system_page.format(_handheld_ids[Handhelds.neo_geo_pocket]),
    Handhelds.neo_geo_pocket_color: _game_system_page.format(_handheld_ids[Handhelds.neo_geo_pocket_color]),
    Handhelds.nintendo_ds: _game_system_page.format(_handheld_ids[Handhelds.nintendo_ds]),
    Handhelds.playstation_portable: _game_system_page.format(_handheld_ids[Handhelds.playstation_portable]),
    Handhelds.playstation_portable_video: _game_system_page.format(_handheld_ids[Handhelds.playstation_portable_video]),
    Handhelds.playstation_vita: _game_system_page.format(_handheld_ids[Handhelds.playstation_vita]),
    Handhelds.virtual_boy: _game_system_page.format(_handheld_ids[Handhelds.virtual_boy]),
    Handhelds.wonderswan: _game_system_page.format(_handheld_ids[Handhelds.wonderswan]),
    Handhelds.wonderswan_color: _game_system_page.format(_handheld_ids[Handhelds.wonderswan_color]),
}

_computer_ids = {
    Computers.amiga: 57,
    Computers.linux: 25,
    Computers.mac: 26,
    Computers.ms_dos: 28,
    Computers.windows: 24,
}
computers = {
    Computers.amiga: _game_system_page.format(_computer_ids[Computers.amiga]),
    Computers.linux: _game_system_page.format(_computer_ids[Computers.linux]),
    Computers.mac: _game_system_page.format(_computer_ids[Computers.mac]),
    Computers.ms_dos: _game_system_page.format(_computer_ids[Computers.ms_dos]),
    Computers.windows: _game_system_page.format(_computer_ids[Computers.windows]),
}

game_systems = consoles | handhelds | computers
