from thecoverproject import Console, Handheld, Computer

home = "http://thecoverproject.net"
index_opt = "&view={}"
game_page = home + "/view.php?game_id={}"
_game_system_page = home + "/view.php?cat_id={}"

_console_ids = {
    Console.three_do: 40,
    Console.amiga_cd_thirty_two: 48,
    Console.atari_two_six_zero_zero: 36,
    Console.atari_five_two_zero_zero: 34,
    Console.atari_seven_eight_zero_zero: 39,
    Console.atari_jaguar: 33,
    Console.atari_xe: 35,
    Console.colecovision: 38,
    Console.dreamcast: 1,
    Console.famicom_disk_system: 41,
    Console.gamecube: 2,
    Console.genesis: 3,
    Console.intellivision: 31,
    Console.jaguar_cd: 37,
    Console.neo_geo_cd: 32,
    Console.nes: 27,
    Console.nintendo_sixty_four: 4,
    Console.nintendo_switch: 62,
    Console.nintendo_wii: 18,
    Console.nintendo_wii_u: 58,
    Console.odyssey_two: 61,
    Console.pc_fx: 43,
    Console.philips_cdi: 51,
    Console.playstation_one: 5,
    Console.playstation_two: 6,
    Console.playstation_three: 19,
    Console.playstation_four: 60,
    Console.playstation_five: 63,
    Console.sega_thirty_two_x: 29,
    Console.sega_cd: 17,
    Console.sega_master_system: 30,
    Console.sega_saturn: 7,
    Console.super_nintendo: 8,
    Console.turbografx_sixteen: 42,
    Console.xbox: 9,
    Console.xbox_three_six_zero: 10,
    Console.xbox_one: 59,
    Console.xbox_series_x: 64,
}
consoles = {
    Console.three_do: _game_system_page.format(_console_ids[Console.three_do]),
    Console.amiga_cd_thirty_two: _game_system_page.format(_console_ids[Console.amiga_cd_thirty_two]),
    Console.atari_two_six_zero_zero: _game_system_page.format(_console_ids[Console.atari_two_six_zero_zero]),
    Console.atari_five_two_zero_zero: _game_system_page.format(_console_ids[Console.atari_five_two_zero_zero]),
    Console.atari_seven_eight_zero_zero: _game_system_page.format(_console_ids[Console.atari_seven_eight_zero_zero]),
    Console.atari_jaguar: _game_system_page.format(_console_ids[Console.atari_jaguar]),
    Console.atari_xe: _game_system_page.format(_console_ids[Console.atari_xe]),
    Console.colecovision: _game_system_page.format(_console_ids[Console.colecovision]),
    Console.dreamcast: _game_system_page.format(_console_ids[Console.dreamcast]),
    Console.famicom_disk_system: _game_system_page.format(_console_ids[Console.famicom_disk_system]),
    Console.gamecube: _game_system_page.format(_console_ids[Console.gamecube]),
    Console.genesis: _game_system_page.format(_console_ids[Console.genesis]),
    Console.intellivision: _game_system_page.format(_console_ids[Console.intellivision]),
    Console.jaguar_cd: _game_system_page.format(_console_ids[Console.jaguar_cd]),
    Console.neo_geo_cd: _game_system_page.format(_console_ids[Console.neo_geo_cd]),
    Console.nes: _game_system_page.format(_console_ids[Console.nes]),
    Console.nintendo_sixty_four: _game_system_page.format(_console_ids[Console.nintendo_sixty_four]),
    Console.nintendo_switch: _game_system_page.format(_console_ids[Console.nintendo_switch]),
    Console.nintendo_wii: _game_system_page.format(_console_ids[Console.nintendo_wii]),
    Console.nintendo_wii_u: _game_system_page.format(_console_ids[Console.nintendo_wii_u]),
    Console.odyssey_two: _game_system_page.format(_console_ids[Console.odyssey_two]),
    Console.pc_fx: _game_system_page.format(_console_ids[Console.pc_fx]),
    Console.philips_cdi: _game_system_page.format(_console_ids[Console.philips_cdi]),
    Console.playstation_one: _game_system_page.format(_console_ids[Console.playstation_one]),
    Console.playstation_two: _game_system_page.format(_console_ids[Console.playstation_two]),
    Console.playstation_three: _game_system_page.format(_console_ids[Console.playstation_three]),
    Console.playstation_four: _game_system_page.format(_console_ids[Console.playstation_four]),
    Console.playstation_five: _game_system_page.format(_console_ids[Console.playstation_five]),
    Console.sega_thirty_two_x: _game_system_page.format(_console_ids[Console.sega_thirty_two_x]),
    Console.sega_cd: _game_system_page.format(_console_ids[Console.sega_cd]),
    Console.sega_master_system: _game_system_page.format(_console_ids[Console.sega_master_system]),
    Console.sega_saturn: _game_system_page.format(_console_ids[Console.sega_saturn]),
    Console.super_nintendo: _game_system_page.format(_console_ids[Console.super_nintendo]),
    Console.turbografx_sixteen: _game_system_page.format(_console_ids[Console.turbografx_sixteen]),
    Console.xbox: _game_system_page.format(_console_ids[Console.xbox]),
    Console.xbox_three_six_zero: _game_system_page.format(_console_ids[Console.xbox_three_six_zero]),
    Console.xbox_one: _game_system_page.format(_console_ids[Console.xbox_one]),
    Console.xbox_series_x: _game_system_page.format(_console_ids[Console.xbox_series_x]),
}

_handheld_ids = {
    Handheld.three_ds: 54,
    Handheld.atari_lynx: 44,
    Handheld.game_gear: 15,
    Handheld.gameboy: 12,
    Handheld.gameboy_advance: 13,
    Handheld.gameboy_advance_video: 20,
    Handheld.gameboy_color: 14,
    Handheld.neo_geo_pocket: 45,
    Handheld.neo_geo_pocket_color: 46,
    Handheld.nintendo_ds: 11,
    Handheld.playstation_portable: 16,
    Handheld.playstation_portable_video: 52,
    Handheld.playstation_vita: 55,
    Handheld.virtual_boy: 56,
    Handheld.wonderswan: 47,
    Handheld.wonderswan_color: 50,
}
handhelds = {
    Handheld.three_ds: _game_system_page.format(_handheld_ids[Handheld.three_ds]),
    Handheld.atari_lynx: _game_system_page.format(_handheld_ids[Handheld.atari_lynx]),
    Handheld.game_gear: _game_system_page.format(_handheld_ids[Handheld.game_gear]),
    Handheld.gameboy: _game_system_page.format(_handheld_ids[Handheld.gameboy]),
    Handheld.gameboy_advance: _game_system_page.format(_handheld_ids[Handheld.gameboy_advance]),
    Handheld.gameboy_advance_video: _game_system_page.format(_handheld_ids[Handheld.gameboy_advance_video]),
    Handheld.gameboy_color: _game_system_page.format(_handheld_ids[Handheld.gameboy_color]),
    Handheld.neo_geo_pocket: _game_system_page.format(_handheld_ids[Handheld.neo_geo_pocket]),
    Handheld.neo_geo_pocket_color: _game_system_page.format(_handheld_ids[Handheld.neo_geo_pocket_color]),
    Handheld.nintendo_ds: _game_system_page.format(_handheld_ids[Handheld.nintendo_ds]),
    Handheld.playstation_portable: _game_system_page.format(_handheld_ids[Handheld.playstation_portable]),
    Handheld.playstation_portable_video: _game_system_page.format(_handheld_ids[Handheld.playstation_portable_video]),
    Handheld.playstation_vita: _game_system_page.format(_handheld_ids[Handheld.playstation_vita]),
    Handheld.virtual_boy: _game_system_page.format(_handheld_ids[Handheld.virtual_boy]),
    Handheld.wonderswan: _game_system_page.format(_handheld_ids[Handheld.wonderswan]),
    Handheld.wonderswan_color: _game_system_page.format(_handheld_ids[Handheld.wonderswan_color]),
}

_computer_ids = {
    Computer.amiga: 57,
    Computer.linux: 25,
    Computer.mac: 26,
    Computer.ms_dos: 28,
    Computer.windows: 24,
}
computers = {
    Computer.amiga: _game_system_page.format(_computer_ids[Computer.amiga]),
    Computer.linux: _game_system_page.format(_computer_ids[Computer.linux]),
    Computer.mac: _game_system_page.format(_computer_ids[Computer.mac]),
    Computer.ms_dos: _game_system_page.format(_computer_ids[Computer.ms_dos]),
    Computer.windows: _game_system_page.format(_computer_ids[Computer.windows]),
}

game_systems = consoles | handhelds | computers
